INSERT INTO expense_type (id, type)
VALUES
  (1, 'Rent'),
  (2, 'Electricity'),
  (3, 'Gas'),
  (4, 'Phone'),
  (5, 'Internet'),
  (6, 'Water'),
  (7, 'Savings'),
  (8, 'Investments'),
  (9, 'Mortgage'),
  (10, 'Transportation'),
  (11, 'Restauraunts'),
  (12, 'Groceries'),
  (13, 'Travel'),
  (14, 'Shopping'),
  (15, 'Home'),
  (16, 'Other'),
  (17, 'Charity'),
  (18, 'Beauty'),
  (19, 'Entertainment'),
  (20, 'Gifts'),
  (21, 'Insurance'),
  (22, 'Debt Repayment');

